### ISSUE TITLE
is there a commercial friendly licence?

### ISSUE THREAD

**Issue by aboganas** [nabil-mansouri/nativescript-couchbaselite#4]
Kudos nabil for the nice plugin; However, the adapted AGPL licence really prohibit us from using it in our apps since it will require opening the source code of the app. 

Do you offer commercial licence or are there any plans to change to more friendly licence like MIT

**Comment by foto-andreas** [comment]
Yes, this would be interesting.

**Comment by aboganas** [comment]
anyway this repo seems dead, I started experimenting with 
[https://github.com/couchbaselabs/nativescript-couchbase](url)

**Comment by nabil-mansouri** [comment]
sorry guys i was very very busy on these months... i have changed licence now so you use it under Apche 2 licence

**Comment by foto-andreas** [comment]
cool! thank you!
